### ISSUE TITLE
List of Registry Keys Used and Folders in Windows - Security

### ISSUE THREAD

**Issue by SecurityImportant** [nicehash/NiceHashMinerLegacy#555]
Hi,

I am trying to sandbox NiceHash Legacy the latest stable release for security and confidence in the product. 

I have blocked access to all parts of C except Windows (and Nicehash folder) and have blocked  HKEY_Classes_Root and HKey_Current_Config.

If I block C:\Windows and if I block HKEY_Local_Machine or HKEY_Current_User the program will not run!!!

Can you specify which sub-parts of those registry and C:\Windows your program needs.

I think this is good disclosure and should install greater confidence in the program!

**Comment by DillonN** [comment]
Registry is used for figuring out if some dependencies are installed, the disable Windows error reporting option, as well as activating automatic startup. 

You can see the specific keys in the source code - [Helpers.cs](https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/Utils/Helpers.cs) contains the first two I mentioned and [Form_Settings.cs](https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/Forms/Form_Settings.cs) contains the startup option. Use Ctrl+F Registry to find where they are defined

**Comment by SecurityImportant** [comment]
Thanks for that! 

What about the other 3rd party downloaded programs for the various miners and algos etc?

Also do you know what directories or files in the Windows directory are used e.g. for my NVIDIA miner window if I block the FILE exlporer.exe the cmd window opens and then quickly shuts!

**Comment by SecurityImportant** [comment]
Another option would be to enable this to be virtualized. I can use VMWARE Thinapp or Cameyo to virtualize the NVIDIA V2.0.1.4 Nicehash Miner. Thus really locking the app and ensuring system and data integrity.

When I do it with the Legacy version in Thinapp I get a Forms error with a folder link that incudes your Dillon USER location and the program crashes. Same with Cameyo.

**Comment by SecurityImportant** [comment]
Just did a Microsoft Sysinternals process Monitor check - in just 1 minute your NicehashMinerLagacy.exe did 798,403 registry events, read/write etc!!! Wow! I just filtered for that - if I did it for the cmd mining windows too it would probably be X times greater!

**Comment by SecurityImportant** [comment]
OK - I was surprised to see that NiceHashMiner queiries the registry about 60 THOUSAND times a minute! Some of the query types might be worrying - e.g. it has a mailto check, and it searches all the private certificate locations e.g. Root and CA.

Howerver, as a start these are the common reg locations I have shotened them for blocking e.g.  HKCR\CLSID\ would have other bits after the \. I have left a few extended ones in to ask why it needs to look at such areas of the registry e.g. certificates, mailto, explorer?


HKCR\AppID\NiceHashMinerLegacy.exe
HKCR\Applications\NiceHashMinerLegacy.exe
HKCR\CLSID\
HKCR\Installer\Assemblies\Global
HKCR\Interface\
HKCR\mailto
HKLM\Hardware\DeviceMap\VIDEO
HKLM\Software\Microsoft\
HKLM\software\microsoft\EnterpriseCertificates\CA\Certificates
HKLM\Software\Microsoft\EnterpriseCertificates\CA\PhysicalStores
HKLM\software\microsoft\EnterpriseCertificates\Root\Certificates
HKLM\Software\NiceHash\NiceHashMinerLegacy\1.8.1.5
HKLM\Software\NVIDIA   Corporation\Global\FTS
HKLM\Software\Policies\Microsoft\Cryptography
HKLM\Software\Policies\Microsoft\SystemCertificates\AuthRoot
HKLM\Software\Policies\Microsoft\SystemCertificates\AuthRoot
HKLM\software\policies\microsoft\SystemCertificates\CA\Certificates
HKLM\System\CurrentControlSet\
HKU\{GUID)\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
HKU\{GUID)\mailto

**Comment by nicehashdev** [comment]
You have full source available on GitHub. Except the 3rd party miners which are closed source (not by us) and we do not guarantee any safety using them.

NHM is using C# .NET framework to operate, which means that all I/O or registry actions aren't known by the programmer. Some (such as query for certificates to establish SSL/HTTPS cons) may happen for the needs of the framework itself. If you wish to get more knowledge about that, contact Microsoft.
