### ISSUE TITLE
How long to go before ASIC/GPU Minner Rigs kills regular GPU PC

### ISSUE THREAD

**Issue by SecurityImportant** [nicehash/NiceHashMinerLegacy#566]
Quick question: As ASIC has killed bitcoin mining using normal PCs (even with 5 or so graphics cards) directly.

Nicehash is nice as it does not quite do what ASIC does - it leases your CPU/GPU and pays for the usage time!!!! Great same idea can be used for low-budget cloud computing etc. and get a share of revenue (maybe done already have not checked).

The question is how long do you think NiceHash style mining has using GPUs before ASICs make it not profitable? They are in TH/s and GPUs are a in GH/s or MH/s - big difference. So what is the answer please?

**Comment by nivong** [comment]
this is not an issue... go to bitcoin forum or reddit for this.

**Comment by SecurityImportant** [comment]
Thanks for that reply - maybe a bit more precision? It is like saying go to Google for all answers! :)

**Comment by S74nk0** [comment]
@SecurityImportant Please don't open issues on GitHub that are not related to software code, feature request or current issues related with the software of the repository. For general discussions please go to bitcoin forum or reddit or some other discussion board that is meant for general discussions.

Closing issue not related to the project.
