### ISSUE TITLE
When BTC drops almost 20% in a few hours better to stop worrying about CPU, security for rig etc!

### ISSUE THREAD

**Issue by SecurityImportant** [nicehash/NiceHashMinerLegacy#580]
At current rates, power/GPU/CPU/ deterioration of all electronic devices is a serious matter.

BTC dropped almost $1000.

If constant income per my Watts per hour are not secured then all is a waste of time! My computer, my electricity, my equipment.

Your software should balance such and adjust.

When there is a big drop - NiceHash should suspend commissions (or reduce) and make an immediate payout!

**Comment by jackpot1136** [comment]
you should check out azure Microsoft. It's free for a month plus they will
give you $200 spending money. Instead of punishing those who are moving
faster, we should try move at a higher rate together. Check it out. It's
only getting faster.

**Comment by SecurityImportant** [comment]
Taking a simple home rig - $2-3 a day. With a $1000 per BTC drop i.e about 20% That $2-3 drops to $1-2ish.

But the user's power and equipment costs are the same!

You develop the software to mine (a gui front-end to the CMD miners) - your external algos also take a 1-2+% commission per hour (dual algo). On Withdrawal you take another 0.005 BTC charge (about $3) AND you take a minimum of 2% commission for saving to your wallet. So, total - $3 + 1-2% + 0.0005BTC!!!

After all this you do not care about security etc - as demonstrated by closing many of my posts!

**Comment by luongk** [comment]
@SecurityImportant I think you have a fundamental misunderstanding on how Nicehash works.  They don't determine the payout, the payout is determined by the buyers.

**Comment by SecurityImportant** [comment]
Then make it transparent - buyer is asking for e.g. 1 Mhz at $X price. You keep your share a fare middle-man share and then ask users....

Currently I an having to spend days locking your system for security issues and I find that the payment has dropped by 20%!!!!

Simple, take cpu/GPU lease and pay for such based on a hourly basis - with you making a cut profit in the middle!

**Comment by SecurityImportant** [comment]
Do you actually realize how many security issue there are?

As mentioned, in just 1 minute your software needs to query the registry tens of thousands of times. The locations that the software is looking at are not what is what I would call normal!

Your software initially seeks to see which container it is running in... a deep security issue! And then bounces and does the mining!

Your software almost does a full disk scan! I have had to block it and isolate it to ensure it does not escape! Granted, you may say that external algos are not yours... but the software bundle does such!

**Comment by SecurityImportant** [comment]
Please tell me how almost a MILLION registry queries in 15 minutes is justified by your software?

I had a lovely response regarding dot-net and how MIcrosoft software can do such... Umm,  No no it does not.. As for the crypto side no too!

Can you justify for your software needing to access the private registry of a computer about 100K per minute and can can you justify the locations on personal computer drives that you software has scanned?

**Comment by SecurityImportant** [comment]
In the UK, under the Data Protection Act and the Computer Misuse Act under I am now serving you with CRIMINAL INTERPOL accusations. I also submit you with failure to protect data in the United Kingdom (UK).

I am now asking for your company details in the UK. (it is not a problem if you do not have UK HQ) - the law now permits criminal acts to be prosecuted cross borders!

I could be blunt and say illiterate and those who are ignorant of the lawa may think this post is funny!

The reality needs to be tried using criminal legal justice both in the UK an US!

**Comment by SecurityImportant** [comment]
Detailed legal matters to follow:

Usernames linked to ip address and real name. IP address linked to multi-bounced system - still individual legally responsible and is UK and US legal court liable!

**Comment by SecurityImportant** [comment]
luongk?? 

Please do not insult us! Lovely photo, uploaded this month...

Shall I pass this onto the Chinese authorities that have a very good monitoring system?

**Comment by SecurityImportant** [comment]
Incase you id luon

**Comment by SecurityImportant** [comment]
I am being generous to the developers by modifying and re-opening this!

The issue is that NiceHash is providing code that directly has security implications of a system. This is illegal in the UK, EU and the USA. A disclaimer does not void criminal liability.

I have spent almost 3-4 days scanning your code and can you justify drive scanning, registry scanning, container of NiceHash scanning and more?

I looked in 1 reg location regarding crypto and it was in Chinese the data!

A safe system is a good system and ensures trust! Providing source code is not a way to gain trust e.g. TrueCrypt provided source but nobody was able to replicate the hash. 

Your system is a financial system and should give a user 100% confidence. Have you achieved such?

**Comment by nivong** [comment]
It isn't that difficult to edit a post....

**Comment by jackpot1136** [comment]
What do you want me to do

**Comment by jackpot1136** [comment]
Give it a min I sit it down let me know if it helps
