### ISSUE TITLE
They will try to ban me and will try to ban me - but crooks do such!

### ISSUE THREAD

**Issue by SecurityPoliceWill** [nicehash/NiceHashMinerLegacy#732]
Issue 178/179

@DillonN I think the above is the solution and implicates NH. I think you are innocent and your team - the legal Corpoartion Tax burden of having to repay non-corporation tax customers was in my view the issue for the disappearance of the 4700 BTC.

Good luck with your life - I think the police can now listen to such and act. Puzzles are tricky... all angles must be explored.
 @SecurityImportant
     
SecurityImportant commented 37 minutes ago
For those who do not understand my posts:

An example; You mined 1 BTC in November at price roughly $7000 in December you want payout to your external wallent at the new price of $15K+

Under accounting systems your money is held in NH wallet - so, they are liable for a tax on the gain! This is a roughly 20% - so they will make a 20% loss when paying the miner!

What is 20% of 70 million? $14 million! So to pay the customers they would take a big hit!

Maybe better to have the funds be "stolen?

**Comment by SecurityPoliceWill** [comment]
I am SecurityImportant and I am on the side of the police and Interpol - the dark team at NiceHash have tried to ban me for for many day now!!!

That is OK - it is just an internet site and being banned is the way they operate. The reality is that the police now have good evidence and by banning each post the beneficiaries of criminal matters are shown!

**Comment by SecurityPoliceWill** [comment]
I shall clarify the 20% is on the double of the money! e.g 20 on the difference between $7000 and $15,000 is 0.20 x 8000 = 16,000 per BTC!!!! That is NH loss when payout to you when they closed!

**Comment by SecurityPoliceWill** [comment]
If BTC had not grown so fast then there coimmission was working and all were happy!

The problem was that BTC jumped in 1 month from $7000 to around $15000. It was in their wallet so they are liable for Corporation Tax at the high rate!

So, better to lose the money and close than be liable for such tax charges that are higher than their commission and cut etc!

**Comment by SecurityPoliceWill** [comment]
North Korea is shooting missiles and making Trump Angry - they have better things to do than take a small sum of $70 million. Each rocket costs more  - NichHash blamed North Korea.... in my opinion nonsense.

Taxation killed NH!

**Comment by SecurityPoliceWill** [comment]
Slovenian Tax Calendar is till December 2017 (https://home.kpmg.com/xx/en/home/insights/2011/12/Slovenia-income-tax.html). 

Hmm... only weeks before end company is running for the exit??? Logically they had no choice... can you restructure a full company in less than 21 days now? With all eyes on such?

**Comment by SecurityPoliceWill** [comment]
A company can show beautiful diagrams re: how capital has dispersed under CRYPTO currency. they could show me how money was lost by a greyhound in race 2!

The reality is the COMPANY is the keeper of the the funds of its people!

So, I do not want to see stupid 256bit crypto blockchain addresses and charts! - in reality it is only 128 but....

Anyways!

**Comment by SecurityPoliceWill** [comment]
@microtechies  what is your background son that makes you feel able to contribute to a criminal investigation, a crypto investigation, and a lot more?

**Comment by microtechies** [comment]
The fact that I have dealt with them before, and understand professionalism, something you have shown to lack. Having set up an account with github just to have a moan and show your theory's without proof.

**Comment by SecurityPoliceWill** [comment]
Micro go play with micro toys... 

This is a for bigger fish than you. I have evaluated you in the last hour and you are not at the level required - Have a good Christmas and New Year! Bye!

**Comment by microtechies** [comment]
Haha, you don't know me. Nice to see more of your professionalism

**Comment by SecurityPoliceWill** [comment]
Waste of time child! Best wishes and a happy New Year!

**Comment by microtechies** [comment]
At least I don't hide behind newly setup accounts with no info, because I'm an adult and do not fear small minded conspiracy theorists like you. Enjoy your small minded world

**Comment by Crypto-Lord** [comment]
@microtechies you shouldn't play with trolls, it's like trying to teach a goldfish to sit

**Comment by microtechies** [comment]
@Crypto-Lord I know I give up. Nicehash & Github are on it already I'll leave it to them

**Comment by SecurityPoliceWill** [comment]
Ah provocative : Tomorrow: 3:35 PM Maggie Mays Belfast - Cafe Wear a great rose to show sympathy! 

Ok?

**Comment by SecurityPoliceWill** [comment]
Keep the below in your mind small fish: 2 Malone Rd, Belfast BT9 5BN 3:35 PM!

**Comment by SecurityPoliceWill** [comment]
Goeveinging ng S7nk)

Smart boy - tell your other Github crooks that $60-80 theft will not be forgotten!

I will work legally and very seriously to ensure every participant faces legal justice - nothing illegal. But they fear legal from sides not even many can dream - I can show them those legal sides!

**Comment by SecurityPoliceWill** [comment]
This is reopened!
