### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by wermaxta** [nicehash/NiceHashMinerLegacy#970]
Hi need help My OS is windows 10 64 bit and I'm using NiceHash MIner 1.8.1.8 for AMD.
My problem is yesterday my BTC balance it was 7.11 USD and today when i start the program is show me  6.34 USD.
 
![btc](https://user-images.githubusercontent.com/2546377/35806797-64e9e83c-0a89-11e8-9c2c-9bae7a464a22.jpg)
Thank you .

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by luongk** [comment]
The value of BTC has dropped since you last checked. Your balance hasn't changed, the value of your BTC has.

**Comment by wermaxta** [comment]
luongk Thank you :)
