### ISSUE TITLE
balance problem 

### ISSUE THREAD

**Issue by wermaxta** [nicehash/NiceHashMinerLegacy#981]
hi i have problem with my balance on first picture it was my balance from yesterday
![btc](https://user-images.githubusercontent.com/2546377/36075642-7a73f622-0f5a-11e8-8f5c-5720eeee56cd.jpg)

on second one is from today 
![btc1](https://user-images.githubusercontent.com/2546377/36075655-9f4abefe-0f5a-11e8-831d-1ffae808cb57.jpg)

and this is my balance from my account 0.00112810
and my point is what is going on ????
Thank you 

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by wermaxta** [comment]
This is my logs 
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1714607/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1714608/log.txt)

**Comment by oherman** [comment]
Your BTC wallet is from MH or external? If the former, it's the payout-- check your account and BTC address.
If it's external however, that's something else.
